name: Docker Master (ARM64) Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches:
      - 'master'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Uses our Docker Hub username and access token to log-in
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      # Setup Docker Buildx to create the builder instance using a BuildKit container
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      # Build the image and push it to Docker Hub
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/petio:latest-arm64
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/petio:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/petio:buildcache,mode=max
